[project]
name = "ner-bert-app"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "fastapi[standard]",
    "transformers",
    "torch",         
    "pandas",
    "tenacity",
    "slowapi",
    "grpcio",
    "grpcio-tools",
    "pydantic",
    "datasets>=3.0,<4.0",
    "bioc",
    "evaluate",
    "accelerate",
    "seqeval",
    "numpy",
    "python-multipart",
    "pypdf",
    "python-docx",
    "matplotlib",
    "seaborn"
]

[project.scripts]
evaluate-cased = "model.evals.cased_eval:main"
evaluate-uncased = "model.evals.uncased_eval:main"
train-cased = "model.training.train_cased:main"
train-uncased = "model.training.train_uncased:main"

[build-system]
requires = ["setuptools>=61.0.0"]
build-backend = "setuptools.build_meta"

[tool.ruff]
line-length = 100
target-version = "py311"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q"
testpaths = ["tests"]
pythonpath = ["src"]